language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t goodhat/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true goodhat/docker-react npm run test

deploy:
  provider: gae
  keyfile: $GAE_PRIVATE_KEY
  project: docker-react-284708
  on: 
    branch: master

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-r3ji3vjds"
#   bucket_path: "docker"
#   on:
#     branch: master
